### ISSUE TITLE
Better not to externally link pico_sdk_import

### ISSUE THREAD

**Issue by Wren6991** [pimoroni/pico-boilerplate#3]
From the Readme:

> And then (assuming pico-sdk is alongside your project):
> `ln -s ../pico-sdk/external/pico_sdk_import.cmake .`

`pico_sdk_import` is a small helper that finds the SDK for you based on `PICO_SDK_PATH`, or clones for you based on a git revision. The contents should be stable, and having to explicitly link to a file in an SDK checkout defeats its purpose! Note the comment at the top of `pico_sdk_import.cmake`:

```
# This is a copy of <PICO_SDK_PATH>/external/pico_sdk_import.cmake

# This can be dropped into an external project to help locate this SDK
# It should be include()ed prior to project()
```

If this was included in this repo, it would remove a step from the setup, and also make people's projects a little less fragile, so hopefully easier for everybody all round. If you're ok with this change, I can raise a PR.

**Comment by Gadgetoid** [comment]
Thanks for pointing this out- I had assumed the import file was likely to change in future. Should now be fixed!

**Comment by Wren6991** [comment]
Awesome thank you! I asked internally before raising, the contents should be stable (or at least remain usable in the future).
