### ISSUE TITLE
Cannot compile - Error regarding Explorer::Set_backlight

### ISSUE THREAD

**Issue by Brainz456** [pimoroni/pico-boilerplate#6]
Function pico_explorer::set_backlight(100) on line 14 of main.cpp causes compilation error.

/mnt/c/Users/James/Documents/Programming/pico-dev/pico-test/main.cpp: In function 'int main()':
/mnt/c/Users/James/Documents/Programming/pico-dev/pico-test/main.cpp:14:19: error: 'class pimoroni::PicoExplorer' has no member named 'set_backlight'
   14 |     pico_explorer.set_backlight(100);
      |                   ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/simple_test.dir/build.make:63: CMakeFiles/simple_test.dir/main.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1535: CMakeFiles/simple_test.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by Brainz456** [comment]
Upon further look into the source for Pico_Explorer, there doesn't seem to be a set_backlight function defined at all? Is this a feature to be developed?

**Comment by Gadgetoid** [comment]
There's physically no backlight control on Pico Explorer, the addition of that function was an error and references to it should be dropped from your code.

**Comment by Gadgetoid** [comment]
:eyes: or... dropped from *our* code, as it were! :facepalm:
